name: house_design
description: "House Design - explore templates, plan interiors, and estimate material cost."
publish_to: 'none'
version: 1.1.2+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  http: ^1.2.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  path_provider: ^2.1.6
  gal: ^2.3.3
  flutter_native_splash: ^2.4.7
  url_launcher: ^6.3.0
  pdf: ^3.12.0
  printing: ^5.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # 👇 Yahan sirf folder ka path de diya hai
  assets:
    - assets/images/